name: Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Ruddy2310
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
